defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.7.1

version: 2

jobs:
  checkout-code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install-deps:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-yarn-cache

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn/v1
          key: v5-yarn-cache

      - save_cache:
          paths:
            - node_modules
          key: v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: yarn test

  docs-build:
     <<: *defaults
     steps:
       - restore_cache:
           keys:
             - v5-repo-{{ .Environment.CIRCLE_SHA1 }}
 
       - restore_cache:
           keys:
             - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
 
       - run:
           name: Generate docs to build
           command: npm run docs:build

       - run:
          name: Disable jekyll builds
          command: touch docs/.nojekyll
 
       - run:
           name: Configure CircleCi deployment
           command: |
             git config user.email "icunningham@grove.co"
             git config user.name "CircleCi Doc Deploy Backbone.Store"

       - add_ssh_keys:
           fingerprints:
             - "cf:11:c6:b2:2d:e3:31:b9:a9:ca:18:dd:99:27:ae:ab"

       - run:
           name: Deploy docs to gh-pages branch
           command: |
               mkdir -p ~/.ssh
               touch known_hosts
               ssh-keyscan github.com >> ~/.ssh/known_hosts
               npm run gh-pages-deploy

  publish:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Authenticating NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Publish NPM module
          command: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - checkout-code
      - install-deps:
          requires:
            - checkout-code

      - lint:
          requires:
            - install-deps

      - test:
          requires:
            - install-deps

      - docs-build:
         requires:
           - install-deps

      - publish:
          requires:
            - lint
            - test
            - docs-build
          filters:
            branches:
              only: -none-
              ignore: /^.*$/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
