defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

version: 2

jobs:
  checkout-code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install-deps:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-yarn-cache

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn/v1
          key: v5-yarn-cache

      - save_cache:
          paths:
            - node_modules
          key: v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: yarn test

  docs:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - add_ssh_keys:
          fingerprints:
            - "cf:11:c6:b2:2d:e3:31:b9:a9:ca:18:dd:99:27:ae:ab"

      - checkout

      - run:
          name: Fetch `gh-pages` and set user
          command: |
            git fetch origin gh-pages:gh-pages
            git config user.email "engineering@grove.co"
            git config user.name "CircleCI"

      - run:
          name: Checkout existing `gh-pages` as `docs`
          command: git worktree add docs gh-pages

      - run:
          name: Update `docs` via `npm run build:docs`
          command: npm run build:docs

      - run:
          name: Commit `docs` to `gh-pages`
          command: |
            pushd docs
            git add .
            git commit -m '[skip ci] publishing docs'
            git push origin gh-pages

  publish:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v5-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v5-npm-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Authenticating NPM
          # The registry that this package will be published to is defined within the `package.json`
          command: echo "//npm.pkg.github.com/:_authToken=$NPM_GITHUB_REGISTRY_ACCESS_TOKEN" >> ~/.npmrc

      - run:
          name: Publish NPM module
          command: npm publish

workflows:
  version: 2
  build:
    jobs:
      - checkout-code:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/

      - install-deps:
          requires:
            - checkout-code
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/

      - lint:
          requires:
            - install-deps
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/

      - test:
          requires:
            - install-deps
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/

      - docs:
          requires:
            - install-deps
            - test
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+){2}/

      - publish:
          requires:
            - lint
            - test
            - docs
          filters:
            branches:
              only: -none-
              ignore: /^.*$/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
